// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA7CzNLR6DpFJW5nnayz95xrU-DE1SIhc',
    appId: '1:616802652999:web:bbd588391863a3c5693262',
    messagingSenderId: '616802652999',
    projectId: 'muniafu-bookings',
    authDomain: 'muniafu-bookings.firebaseapp.com',
    storageBucket: 'muniafu-bookings.appspot.com',
    measurementId: 'G-4VNNV998EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4KYzpUUGfFKNCcGMpMFjfGgt4qM607xc',
    appId: '1:616802652999:android:e79c7da85dc1d675693262',
    messagingSenderId: '616802652999',
    projectId: 'muniafu-bookings',
    storageBucket: 'muniafu-bookings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnXN9o_ON-q6hbC4z_JRfyT8jqqOs3G0',
    appId: '1:616802652999:ios:c0ac3f9eafeb3763693262',
    messagingSenderId: '616802652999',
    projectId: 'muniafu-bookings',
    storageBucket: 'muniafu-bookings.appspot.com',
    iosBundleId: 'com.example.bookings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpnXN9o_ON-q6hbC4z_JRfyT8jqqOs3G0',
    appId: '1:616802652999:ios:c0ac3f9eafeb3763693262',
    messagingSenderId: '616802652999',
    projectId: 'muniafu-bookings',
    storageBucket: 'muniafu-bookings.appspot.com',
    iosBundleId: 'com.example.bookings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA7CzNLR6DpFJW5nnayz95xrU-DE1SIhc',
    appId: '1:616802652999:web:8ae149bc17b8d007693262',
    messagingSenderId: '616802652999',
    projectId: 'muniafu-bookings',
    authDomain: 'muniafu-bookings.firebaseapp.com',
    storageBucket: 'muniafu-bookings.appspot.com',
    measurementId: 'G-Y9FC97HFFT',
  );
}
